services:
    web:
        build: ./backend
        command: python3 manage.py runserver 0.0.0.0:8000
        volumes:
            - ./backend:/backend
            - ./backend/db.sqlite3:/backend/db.sqlite3
        ports:
            - "8000:8000"
        environment:
            - DJANGO_SETTINGS_MODULE=backend.settings
            - DJANGO_ALLOWED_HOSTS=localhost,127.0.0.1,.ngrok-free.app