# Generated by Django 5.2.3 on 2025-07-08 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exam',
            old_name='due_at',
            new_name='dueAt',
        ),
    ]
