# Generated by Django 5.2.3 on 2025-07-11 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UpcomingData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=20)),
                ('course_name', models.CharField(max_length=200)),
                ('week', models.CharField(max_length=50)),
                ('remaining_days', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
