# Generated by Django 5.2.3 on 2025-07-15 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upcoming_list', '0003_remove_upcomingdata_last_accessed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upcomingdata',
            name='remaining_days',
        ),
        migrations.AddField(
            model_name='upcomingdata',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
