# Generated by Django 5.2.3 on 2025-07-15 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upcoming_list', '0004_remove_upcomingdata_remaining_days_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upcomingdata',
            name='week',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
