# Generated by Django 5.2.3 on 2025-07-03 14:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='encryptedtoken',
            name='user',
        ),
        migrations.AddField(
            model_name='encryptedtoken',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 7, 3, 14, 52, 51, 670930, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
