# Generated by Django 5.2.3 on 2025-07-08 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_encryptedtoken_user_encryptedtoken_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encryptedtoken',
            name='token',
            field=models.BinaryField(unique=True),
        ),
    ]
