# Generated by Django 5.2.3 on 2025-07-08 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_encryptedtoken_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='encryptedtoken',
            name='username',
            field=models.CharField(default='unknown', max_length=150),
            preserve_default=False,
        ),
    ]
