# Generated by Django 5.2.3 on 2025-07-14 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_encryptedtoken_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='encryptedtoken',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='encryptedtoken',
            name='token',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='encryptedtoken',
            name='username',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
